//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenCryptoConsole
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CryptoDBEntities : DbContext
    {
        public CryptoDBEntities()
            : base("name=CryptoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CryptoMarket> CryptoMarkets { get; set; }
        public virtual DbSet<market> markets { get; set; }
        public virtual DbSet<Chance> Chances { get; set; }
        public virtual DbSet<ExchangeDb> ExchangeDbs { get; set; }
        public virtual DbSet<MarketsDb> MarketsDbs { get; set; }
        public virtual DbSet<PriceDb> PriceDbs { get; set; }
        public virtual DbSet<MarketPairsDistinct> MarketPairsDistincts { get; set; }
    }
}
