//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenCryptoConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExchangeDb
    {
        public int id { get; set; }
        public string exch_id { get; set; }
        public string exch_name { get; set; }
        public string exch_code { get; set; }
        public string exch_fee { get; set; }
        public string exch_trade_enabled { get; set; }
        public string exch_balance_enabled { get; set; }
        public string exch_url { get; set; }
    }
}
