//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenCryptoConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketPairsDistinct
    {
        public string market { get; set; }
        public Nullable<int> count { get; set; }
        public int id { get; set; }
    }
}
