//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RavenCryptoConsole
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceDb
    {
        public int id { get; set; }
        public string exchange { get; set; }
        public string market { get; set; }
        public string last_trade { get; set; }
        public string high_trade { get; set; }
        public string low_trade { get; set; }
        public string current_volume { get; set; }
        public string timestamp { get; set; }
        public string ask { get; set; }
        public string bid { get; set; }
    }
}
